package com.rifsxd.ksunext.ui.theme

import androidx.compose.ui.graphics.Color

val PRIMARY = Color(0xFF8AADF4)           // Catppuccin Blue
val PRIMARY_LIGHT = Color(0xFFB7BDF8)     // Catppuccin Lavender
val SECONDARY_LIGHT = Color(0xFFA6DA95)   // Catppuccin Green

val PRIMARY_DARK = Color(0xFF7DC4E4)      // Catppuccin Sky
val SECONDARY_DARK = Color(0xFFF5BDE6)    // Catppuccin Pink

val AMOLED_BLACK = Color(0xFF000000)      // Pure black for AMOLED

val DARK_PURPLE = Color(0xFF6E6CB6)       // Catppuccin Mauve (dark purple)
val DARK_GREY = Color(0xFF363A4F)         // Catppuccin Surface (dark grey)

val GREEN = Color(0xFF4CAF50)             // Green
val RED = Color(0xFFF44336)               // Red
val YELLOW = Color(0xFFFFEB3B)            // Yellow
val ORANGE = Color(0xFFFF9800)            // Orange

// Catppuccin Latte — light scheme roles
val LATTE_BLUE = Color(0xFF1E66F5)
val LATTE_ON_BLUE = Color(0xFFFFFFFF)
val LATTE_BLUE_CONTAINER = Color(0xFFDBE4FE)
val LATTE_ON_BLUE_CONTAINER = Color(0xFF06266E)

val LATTE_LAVENDER = Color(0xFF5A6FE8)
val LATTE_ON_LAVENDER = Color(0xFFFFFFFF)
val LATTE_LAVENDER_CONTAINER = Color(0xFFE1E4FF)
val LATTE_ON_LAVENDER_CONTAINER = Color(0xFF161E62)

val LATTE_TEAL = Color(0xFF177F86)
val LATTE_ON_TEAL = Color(0xFFFFFFFF)
val LATTE_TEAL_CONTAINER = Color(0xFFCBEBED)
val LATTE_ON_TEAL_CONTAINER = Color(0xFF00312F)

val LATTE_RED = Color(0xFFD20F39)
val LATTE_ON_RED = Color(0xFFFFFFFF)
val LATTE_RED_CONTAINER = Color(0xFFFBDBE0)
val LATTE_ON_RED_CONTAINER = Color(0xFF5C0616)

val LATTE_BASE = Color(0xFFEFF1F5)
val LATTE_MANTLE = Color(0xFFE6E9EF)
val LATTE_CRUST = Color(0xFFDCE0E8)
val LATTE_TEXT = Color(0xFF4C4F69)
val LATTE_SUBTEXT = Color(0xFF5C5F77)
val LATTE_OVERLAY = Color(0xFF9CA0B0)
val LATTE_SURFACE0 = Color(0xFFCCD0DA)

// Catppuccin Macchiato — dark scheme roles
val MACCHIATO_BLUE = Color(0xFF8AADF4)
val MACCHIATO_ON_BLUE = Color(0xFF0C2757)
val MACCHIATO_BLUE_CONTAINER = Color(0xFF2A4278)
val MACCHIATO_ON_BLUE_CONTAINER = Color(0xFFDBE4FE)

val MACCHIATO_LAVENDER = Color(0xFFB7BDF8)
val MACCHIATO_ON_LAVENDER = Color(0xFF1B2263)
val MACCHIATO_LAVENDER_CONTAINER = Color(0xFF383F80)
val MACCHIATO_ON_LAVENDER_CONTAINER = Color(0xFFE1E4FF)

val MACCHIATO_TEAL = Color(0xFF8BD5CA)
val MACCHIATO_ON_TEAL = Color(0xFF00352F)
val MACCHIATO_TEAL_CONTAINER = Color(0xFF1E4E48)
val MACCHIATO_ON_TEAL_CONTAINER = Color(0xFFCBEBED)

val MACCHIATO_RED = Color(0xFFED8796)
val MACCHIATO_ON_RED = Color(0xFF4C0413)
val MACCHIATO_RED_CONTAINER = Color(0xFF78212F)
val MACCHIATO_ON_RED_CONTAINER = Color(0xFFFBDBE0)

val MACCHIATO_BASE = Color(0xFF24273A)
val MACCHIATO_MANTLE = Color(0xFF1E2030)
val MACCHIATO_CRUST = Color(0xFF181926)
val MACCHIATO_TEXT = Color(0xFFCAD3F5)
val MACCHIATO_SUBTEXT = Color(0xFFB8C0E0)
val MACCHIATO_OVERLAY = Color(0xFF6E738D)
val MACCHIATO_SURFACE1 = Color(0xFF494D64)
val MACCHIATO_SURFACE_LOW = Color(0xFF1E2030)
val MACCHIATO_SURFACE_MID = Color(0xFF292C3E)
val MACCHIATO_SURFACE_HIGH = Color(0xFF313447)
