name: Build Manager (Test)


on:
  push:
    branches: [ "Test" ]
    paths:
      - 'manager/**'
      - 'kernel/**'
      - 'userspace/**'
      - '.github/workflows/manager-test.yml'
  workflow_dispatch:

jobs:
  manager:
    uses: ./.github/workflows/build-manager-ci.yml
    secrets: inherit
